
@hostport=127.0.0.1:8080
@entity=user
@uuid=3a2ff586-f101-497f-955c-6e1090bcda48


####
POST http://{{hostport}}/{{entity}}/ HTTP/1.1
Content-Type: application/json

{
  "uid": "3a2ff586-f101-497f-955c-6e1090bcda48",
  "username": "ryan@starj.org",
  "password": "Password1",
  "firstName": "Ryan",
  "lastName": "World",
  "dayOfBirth": "20020531",
  "use": true
}

####
GET http://{{hostport}}/{{entity}} HTTP/1.1
Content-Type: application/json

####
GET http://{{hostport}}/{{entity}}/{{uuid}} HTTP/1.1
Content-Type: application/json


####
PUT http://{{hostport}}/{{entity}} HTTP/1.1
Content-Type: application/json

{
  "uid": "{{uuid}}",
  "username": "ryan@starj.org",
  "password": "Password1",
  "firstName": "Ryan",
  "lastName": "World",
  "dayOfBirth": "20020531",
  "use": true
}

####
PUT http://{{hostport}}/{{entity}}/{{uuid}} HTTP/1.1
Content-Type: application/json

{
  "username": "ryan@starj.org",
  "password": "******",
  "firstName": "Ryan",
  "lastName": "World",
  "dayOfBirth": "20020531",
  "use": false
}

####
PATCH http://{{hostport}}/{{entity}}/{{uuid}} HTTP/1.1
Content-Type: application/json-patch+json

[
    {"op":"replace","path":"/password","value":"5678"}
]

####
PATCH http://{{hostport}}/{{entity}}/{{uuid}} HTTP/1.1
Content-Type: application/json

{
  "lastName": "Happy Together",
  "use": false
}


####
DELETE http://{{hostport}}/{{entity}}/{{uuid}} HTTP/1.1
Content-Type: application/json


