
@hostport=127.0.0.1:8080
@entity=user
@uuid=20db2306-624e-41f5-b11c-36c91ea314c0


####
POST http://{{hostport}}/{{entity}}/ HTTP/1.1
Content-Type: application/json

{
  "username": "ryan@abc.com",
  "password": "1234",
  "firstName": "Ryan",
  "lastName": "Happy",
  "dayOfBirth": "20220823",
  "use": true
}

####
GET http://{{hostport}}/{{entity}} HTTP/1.1
Content-Type: application/json

####
GET http://{{hostport}}/{{entity}}/{{uuid}} HTTP/1.1
Content-Type: application/json


####
PUT http://{{hostport}}/{{entity}} HTTP/1.1
Content-Type: application/json

{
  "uid": "{{uuid}}",
  "username": "ryan@abc.com",
  "password": "5678",
  "firstName": "Ryan",
  "lastName": "Happy",
  "dayOfBirth": "20220823",
  "use": true
}

####
PUT http://{{hostport}}/{{entity}}/{{uuid}} HTTP/1.1
Content-Type: application/json

{
  "username": "ryan@abc.com",
  "password": "5678",
  "firstName": "Ryan",
  "lastName": "Happy is a dog.",
  "dayOfBirth": "20220823",
  "use": false
}

####
PATCH http://{{hostport}}/{{entity}}/{{uuid}} HTTP/1.1
Content-Type: application/json-patch+json

[
    {"op":"replace","path":"/password","value":"5678"}
]

####
PATCH http://{{hostport}}/{{entity}}/{{uuid}} HTTP/1.1
Content-Type: application/json

{
  "lastName": "Happy Together",
  "use": false
}


####
DELETE http://{{hostport}}/{{entity}}/{{uuid}} HTTP/1.1
Content-Type: application/json


